# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='\u5bc6\u7801'),
        ),
    ]
