# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20171009_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headImg',
            field=models.FileField(null=True, upload_to=b'./upload/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
